# Generated by Django 4.0.2 on 2022-10-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcoin',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
